# Site settings
author: Stefanie Davis
title: 
header-img: img/home-bg.png
email: davisstefanie2010@gmail.com
copyright_name: Stefanie Davis
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: StefLikeCurry
github_username:  stef-codes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
